### ISSUE TITLE
Everything needs to resync after restart project

### ISSUE THREAD

**Issue by rbouma** [cweagans/ddev-mutagen#3]
When i stop my project, all files are removed from docker container.

Then i need to restart my project and it needs to resync all files, we work with Magento 2 and thats a lot of files it takes about 4 to 5 minutes to fully sync my files.

Is there a way to that the files persist on the docker container?

**Comment by cweagans** [comment]
Unfortunately, this is not possible. When ddev projects are stopped, the container is deleted, so the files inside get deleted too.

**Comment by rbouma** [comment]
Alright good to know

First i had the same problem as in this pull request: https://github.com/cweagans/ddev-mutagen/pull/1

The fix in this pull request fixed this issue, so maybe you can accept the pull request for others.

But besides that it works great now, thanks for making this integration 😄

**Comment by wekommerce** [comment]
> Unfortunately, this is not possible. When ddev projects are stopped, the container is deleted, so the files inside get deleted too.

Is there any ways to prevent this to happening? It's frustrating to restart and not being able to run the app again without setting up the whole system via ddev again :S
