### ISSUE TITLE
Running ddev pause wipes out the project

### ISSUE THREAD

**Issue by GerardKetuma** [cweagans/ddev-mutagen#5]
There is an open issue where the Op states that running `ddev stop` and `ddev start` causes the files to sync up again which takes some time. So I decided to run `ddev pause` which stops the containers but does not delete them. Upon running `ddev start`, everything gets wiped out. Lost everthing in my web folder for the ddev project.
So running `ddev pause` and running `ddev start` will wipe out most files in the project. It seems the 2 way sync gets mixed up and we get synced from an empty container.

**Comment by cweagans** [comment]
Ah, that's not good. I've seen this happen, but haven't been able to narrow down what causes it. I've also seen two `ddev start` in a row cause it, but not reliably. Thanks for the issue. I may not have time to resolve in the near future, but happy to look at a PR if you want to submit one!
